"""create parcels table

Revision ID: 67d03a93c51c
Revises: 
Create Date: 2025-07-16 17:56:36.579429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d03a93c51c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('sender_name', sa.String(length=64), nullable=True),
    sa.Column('sender_phone_number', sa.String(length=32), nullable=True),
    sa.Column('pickup_location_text', sa.String(length=255), nullable=True),
    sa.Column('destination_location_text', sa.String(length=255), nullable=True),
    sa.Column('pick_up_longitude', sa.Float(), nullable=True),
    sa.Column('pick_up_latitude', sa.Float(), nullable=True),
    sa.Column('destination_longitude', sa.Float(), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=True),
    sa.Column('current_location_longitude', sa.Float(), nullable=True),
    sa.Column('current_location_latitude', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_name', sa.String(length=64), nullable=True),
    sa.Column('recipient_phone_number', sa.String(length=32), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcels')
    # ### end Alembic commands ###
